### PR TITLE
Update AuthContext.js

### PR DESCRIPTION
**Pull request by ajitmp**
Updated import for jwtDecode for latest version.

### CODE REVIEW

**Comment by ajitmp** [comment]
The import for jwt-decode was throwing error, so changed.

**Comment by ajitmp** [comment]
// With wrong credentials the code get stuck with parsing error message
        // because the response has text message not the access and request tocken in required format
        // performing a check on success of login will prevent this error.
        // a robust error handling can be implemented but below modification a work around to carry on with the tutorial

**Comment by ajitmp** [comment]
Request for handling few errors while following the article

**Review by seankwarren — APPROVED** [review]
These changes LGTM! thanks for updating the import and adding that additional check

**Pull request merged**
